### ISSUE TITLE
Add this feature of pushing the Leetcode problems answers to Github repo

### ISSUE THREAD

**Issue by akshayjadhav2002** [AtharvaNanavate/GfG-To-GitHub#13]
I am suggesting the implementation of a feature that allows users to seamlessly push their LeetCode problem solutions to our GitHub repository. The primary goal is to streamline the process for developers to archive and share their solutions with the community.

**Comment by AtharvaNanavate** [comment]
Hi, Akshay!

This is not planned as of now.
