### ISSUE TITLE
Only Readme file is being created

### ISSUE THREAD

**Issue by samyakagarwal20** [AtharvaNanavate/GfG-To-GitHub#14]
I just installed the extension and linked to an existing repo.

Post that I submitted the solution for a random problem on GFG.

The count of the problem along with its category is updated successfully in the extension itself.

But, the code is not getting synced into the github repo. Only the Readme.md file for that problem is being created.

https://github.com/samyakagarwal20/GFG-Slayer/blob/master/Basic/Find%20minimum%20and%20maximum%20element%20in%20an%20array/README.md

This is the path of the Readme.md file being created.

**Comment by AtharvaNanavate** [comment]
Hi, Samyak!

I was not able to reproduce this issue for the GfG problem mentioned by you. Can you try submitting again? Let me know if you encounter the same issue again.
