### ISSUE TITLE
Solution which is updated is not pushed to the github

### ISSUE THREAD

**Issue by Viraj-Tandel** [AtharvaNanavate/GfG-To-GitHub#16]
Let's say we solved a problem using a brute force approach and successfully submitted the solution to GitHub. However, when I solve the same problem again and attempt to submit it, it is not pushed to GitHub. Please let me know if this issue is due to a problem with my browser or if this kind of functionality is not supported.

**Comment by AtharvaNanavate** [comment]
Hi Viraj! This functionality is supported. 
Can you share the screenshot of your browser console after submitting the new solution so I can better understand what's going on?
