### ISSUE TITLE
GFG-To-Github Extension Pushing Solutions to Incorrect Repositories

### ISSUE THREAD

**Issue by coolsyntax** [AtharvaNanavate/GfG-To-GitHub#8]
I am currently using two extensions on my Brave browser: LeetHub and GFG-To-Github. The purpose of LeetHub is to push LeetCode solutions to a repository named "leetcode," while GFG-To-Github is intended for pushing GeeksforGeeks (GFG) solutions to a repository named "GFG_solutions."

However, I have encountered an issue where the GFG-To-Github extension is pushing solutions to both the "leetcode" repository and the "GFG_solutions" repository. This behavior is unintended and causes confusion, as the solutions should be pushed to their respective repositories only.

I would appreciate it if the developers could investigate and address this issue, ensuring that the GFG-To-Github extension functions correctly and pushes GFG solutions exclusively to the "GFG_solutions" repository.

Thank you for your attention to this matter.

**Comment by AtharvaNanavate** [comment]
I understand your concern. But, this extension cannot push to any repositories other than the one linked to it. The issue you're experiencing appears to be caused by the other extension mentioned.
